<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>YipaSUOfflinePatcher</AssemblyName>
    <RootNamespace>YipaSUOfflinePatcher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="assets\ksud.exe" LogicalName="YipaSUOfflinePatcher.ksud.exe" />
  </ItemGroup>
</Project>
