package com.wutong.wtlyf.license.generator;

import android.app.Activity; import android.graphics.Color; import android.graphics.drawable.GradientDrawable; import android.os.Bundle; import android.text.InputType; import android.view.Gravity; import android.widget.*;
import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import org.json.*;

public final class MainActivity extends Activity {
    private static final String URL="https://wtlyf-license-center.creamy-bowl-8571.chatgpt.site/api/admin/generate";
    private EditText token,count; private TextView output,status;
    @Override public void onCreate(Bundle b){super.onCreate(b); LinearLayout root=base(); TextView title=text("wtlyf 卡密生成器",30,Color.WHITE); title.setTypeface(null,1); root.addView(title); root.addView(text("单卡单设备 · 安全生成",14,Color.rgb(143,174,207))); root.addView(space(28)); LinearLayout card=card(); token=input("管理员令牌");token.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);card.addView(token);count=input("生成数量（1-100）");count.setInputType(InputType.TYPE_CLASS_NUMBER);count.setText("1");card.addView(count);Button go=button("生成卡密");card.addView(go);status=text("等待操作",13,Color.rgb(111,154,190));card.addView(status);output=text("生成结果将在这里显示",15,Color.WHITE);output.setTextIsSelectable(true);output.setPadding(20,20,20,20);output.setBackground(round(Color.argb(110,2,10,25),18));card.addView(output,new LinearLayout.LayoutParams(-1,-2));root.addView(card);go.setOnClickListener(v->{go.setEnabled(false);status.setText("正在生成…");new Thread(()->{try{JSONObject body=new JSONObject().put("count",Integer.parseInt(count.getText().toString()));JSONObject r=post(body,token.getText().toString());runOnUiThread(()->{if(r.optBoolean("ok")){JSONArray a=r.optJSONArray("codes");StringBuilder s=new StringBuilder();if(a!=null)for(int i=0;i<a.length();i++)s.append(a.optString(i)).append('\n');output.setText(s);status.setText("生成成功，仅本次明文显示");}else status.setText(r.optString("message","生成失败"));go.setEnabled(true);});}catch(Exception e){runOnUiThread(()->{status.setText("请求失败："+e.getMessage());go.setEnabled(true);});}},"license-generator").start();});setContentView(scroll(root));}
    private JSONObject post(JSONObject body,String key)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(URL).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(15000);c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Authorization","Bearer "+key.trim());c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}InputStream in=c.getResponseCode()>=400?c.getErrorStream():c.getInputStream();StringBuilder s=new StringBuilder();if(in!=null)try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){for(String l;(l=r.readLine())!=null;)s.append(l);}return new JSONObject(s.length()==0?"{}":s.toString());}
    private LinearLayout base(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(28,60,28,40);l.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(5,11,27),Color.rgb(14,29,57),Color.rgb(29,18,60)}));return l;}private LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(24,24,24,24);l.setBackground(round(Color.argb(205,15,29,55),26));return l;}private EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setHintTextColor(Color.rgb(116,143,174));e.setTextColor(Color.WHITE);e.setBackground(round(Color.argb(150,2,10,25),16));e.setPadding(18,16,18,16);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,14);e.setLayoutParams(p);return e;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setBackground(round(Color.rgb(55,104,210),18));return b;}private TextView text(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(0,8,0,8);return v;}private Space space(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,h));return s;}private GradientDrawable round(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(r);d.setStroke(1,Color.argb(80,130,210,255));return d;}private ScrollView scroll(LinearLayout l){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(l);return s;}
}

