<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>YipaSULicenseSigner</AssemblyName>
    <RootNamespace>YipaSULicenseSigner</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="private.key" LogicalName="YipaSULicenseSigner.private.key" />
  </ItemGroup>
</Project>
